name: Cowsay-workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Install Cowsay program
        run: |
          sudo apt-get update
          sudo apt-get install cowsay

      - name: Run cowsay
        run: |
          cowsay -f dragon "Hello World!" >> hello.txt
          cat hello.txt
          ls -ltra