name: Cowsay-workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: run Cowsay program
        run: |
            chmod +x dragon-script.sh
            ./dragon-script.sh