name: Docker workflow

on: push

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        - name: docker build
          run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.USER_NAME}}/${{ env.IMAGE_NAME }}

        - name: docker login
          run: echo docker login --user=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

        - name: docker publish
          run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.USER_NAME}}/${{ env.IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: docker run
          run: echo docker  run -p 80:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.USER_NAME}}/${{ env.IMAGE_NAME }}